### ISSUE TITLE
Menu Structure

### ISSUE THREAD

**Issue by rasjani** [rasjani/plugin.video.telkkarista_com#1]
Implement initial menu structure with all the features:
- Live Channels
  - ...list of channels ..
- Programs
  - Channels
    - Today
    - Yesterday
    - This Week
    - All
- Movies
  - ... list of movies
- Search
  - title Search
    - New Search
      - ... Search Results
    - ... Old Searches
  - keyword search
    - New Search
      - ... Search Results
    - ... Old Searches

**Comment by rasjani** [comment]
Live Channels: Done
Movies: Done
Programs: Done
Search: No Started

**Comment by rasjani** [comment]
titleSearch is not doable at the moment  because api endpoint doesnt seem to work ..

**Comment by grinsted** [comment]
One option would be to re-order search results client side depending on whether the keywords are in title.
