### ISSUE TITLE
dateutil.tz.gettz - returns none on windows for Europe/Helsinki

### ISSUE THREAD

**Issue by rasjani** [rasjani/plugin.video.telkkarista_com#14]
22:07:12 T:3704   ERROR: C:\Users\Sami\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\zoneinfo__init__.py:36: UserWarning: I/O error(2): No such file or directory
                                              warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
22:07:12 T:3704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: astimezone() argument 1 must be datetime.tzinfo, not None
                                            Traceback (most recent call last):
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\addon.py", line 7, in <module>
                                                telkkarista = Client('telkkarista.com', plugin, xbmcgui, xbmc)
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\client\client.py", line 93, in **init**
                                                self.handleLogin()
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\client\client.py", line 272, in handleLogin
                                                self.ui.cacheHostDialog()
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\client\ui.py", line 117, in cacheHostDialog
                                                hostList = self.SpeedTestDialog(self._client._cacheServers['payload'])
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\client\ui.py", line 106, in SpeedTestDialog
                                                results = self._client.Cache.speedTest(server)
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\api\cache.py", line 28, in speedTest
                                                speedTestStart = utils.unixtimestampms(utils.now())
                                              File "C:\Users\Sami\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com\resources\lib\utils.py", line 65, in now
                                                return datetime.datetime.now(dateutil.tz.tzlocal()).astimezone(dateutil.tz.gettz('Europe/Helsinki'))
                                            TypeError: astimezone() argument 1 must be datetime.tzinfo, not None
                                            -->End of Python script error report<--

**Comment by grinsted** [comment]
The following works in my windows version of python (which is an anaconda install)

import dateutil.tz
import datetime
tz=dateutil.tz.gettz('Europe/Helsinki')
datetime.datetime.now(dateutil.tz.tzlocal()).astimezone(tz)

I cannot test in kodi for windows.

**Comment by rasjani** [comment]
I'll pass that to my dedicated windows guy - he can test it earliest on sunday thou..

**Comment by rasjani** [comment]
Additional errors regarding python and date errors:

163 23:19:40 T:7812  NOTICE: -->Python Interpreter Initialized<--
164 23:19:41 T:7812   ERROR: C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\zoneinfo__init__.py:36: UserWarning: I/O error(2): No such file or directory
165                                               warnings.warn("I/O error({0}): {1}".format(e.errno, e.strerror))
166 23:19:41 T:7812   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
167                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
168                                             Error Type: <type 'exceptions.TypeError'>
169                                             Error Contents: astimezone() argument 1 must be datetime.tzinfo, not None
170                                             Traceback (most recent call last):
171                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\addon.py", line 3, in <module>
172                                                 from resources.lib import Client
173                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib__init__.py", line 2, in <module>
174                                                 from .client import Client
175                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\client__init__.py", line 5, in <module>
176                                                 from .client import Client
177                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\client\client.py", line 5, in <module>
178                                                 from ..api import User
179                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\api__init__.py", line 4, in <module>
180                                                 from .user import User
181                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\api\user.py", line 4, in <module>
182                                                 from .apibase import APIBaseMixin
183                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\api\apibase.py", line 11, in <module>
184                                                 class APIBaseMixin(object):
185                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\api\apibase.py", line 15, in APIBaseMixin
186                                                 lastCall = utils.unixtimestampms() / 1000
187                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\utils.py", line 91, in unixtimestampms
188                                                 dt = now()
189                                               File "C:\Users\FOOBAR_000\AppData\Roaming\Kodi\addons\plugin.video.telkkarista_com-master\resources\lib\utils.py", line 65, in now
190                                                 return datetime.datetime.now(dateutil.tz.tzlocal()).astimezone(dateutil.tz.gettz('Europe/Helsinki'))
191                                             TypeError: astimezone() argument 1 must be datetime.tzinfo, not None
192                                             -->End of Python script error report<--
193 23:19:41 T:2380   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.telkkarista_com/

**Comment by rasjani** [comment]
The issue in above error seems to be this:

dateutil.tz.gettz('Europe/Helsinki') returns None intead of actual timezone in datetime.tzinfo type. I've not seen this happen as i don't have access to windows machine for testing purposes.

1) Does windows have tz database
2) if yes, does it have entry for Europe/Helsinki or should i use something else ? 
3) If it doesnt, how should the UTC timestamps in the epg data be converted to finnish times ?

**Comment by rasjani** [comment]
Above fix seems to work atleast on Windows .. Does anyone happen to have a android device with kodi and bit of time if the master branch is working for them ?
