### ISSUE TITLE
Please add option to use mp4 instead of m3u8 

### ISSUE THREAD

**Issue by grinsted** [rasjani/plugin.video.telkkarista_com#16]
I added such an option in my plugin. It allows you to stream from the download links instead of the m3u8. Seeking works much better with mp4 files.

**Comment by rasjani** [comment]
Yes, i will do that .. Another reason is that i get audio sync issues myself with HLS streams

**Comment by rasjani** [comment]
not super nicely testested yet but should propably do the job.
