### ISSUE TITLE
Consider official kodi repo

### ISSUE THREAD

**Issue by grinsted** [rasjani/plugin.video.telkkarista_com#18]
I think one of our two plugins should go to the official repo. I agree that your plugin is cleaner, plus yours have many more commits and appear to be more experienced at managing these kinds of projects. 

I was also looking at xbmcswift2 when tvkaista closed and I started making a telkkarista plugin. But some things held me back:
- several years since last xbmcswift2 commit. 
- would it be overkill for the relatively small number of features needed. It just seemed like it should fit in a single py file.
- smaller effort as I was already familiar with the design of the tvkaista.

Anyway I like how yours turned out.

**Comment by rasjani** [comment]
1) Official repo is in very much indeed in consideration. I fixed reddit plugin for the reason of actually  just verifying how i get stuff in and work out the process to get kaista also. Few kinks i want to iron out still and then i'll push this forward..

2) been actually playing with idea to fork xbmcswift2 and integrate all the patches in other forks and fix couple of my own and submit that too =)

3) reason why i went with multi file approach was just to learn Python. I hate the language but its still good to know how to code with it =)

**Comment by rasjani** [comment]
Initial integration request from tag v0.9.3 has been send to xmbc-addons mailing list ..
