### ISSUE TITLE
Plug-in flashes "unknown error" and does not start.

### ISSUE THREAD

**Issue by Espanja** [rasjani/plugin.video.telkkarista_com#19]
Have downloaded zip-file and it installs ok. When trying to open it flashes "Unknown error" and would not start. Using tv.box with Android 4.4.2. SOC is Rockchip rk3288 with ARM Cortex-A17 processor and ARM Mali-T624 GPU. What has gone wrong?

**Comment by rasjani** [comment]
Verified, same happens with Isengard 15.1 and OSX ..

**Comment by rasjani** [comment]
The issue  is that there's no check if the settings have been created or not. Thus when initial start of the addon happens, without settings, addon makes a api call to populate cache servers and fails because there's no user credentials or rest of the settings are still uninitialized.

**Comment by rasjani** [comment]
@Espanja: could you try this one: https://github.com/rasjani/plugin.video.telkkarista_com/archive/preventLoginWithoutCredentials.zip and report back any findings ?

**Comment by Espanja** [comment]
Hello! This versions works like a charm  on Android, but so did the one I downloaded on October 14th!! Neither version works on Windows 10 though. 

I have a request. Can the sort order be changed so that the latest recorded programs would appear first (Programs and Search)? Especially in Search if a program has many editions (ex. Uusi Päivä) it is very troublesome to scroll through many pages in order to find the one you would like to watch. The probability that it is a more recent than an older one is imminent.

Thanks for your endevour!

Regards

Alf Heikkinen (Espanja)
