### ISSUE TITLE
Investigate server side throttling.

### ISSUE THREAD

**Issue by rasjani** [rasjani/plugin.video.telkkarista_com#4]
I hit a snack that when quering epg/info for all the movies, backend started to timeout for period of X .. Investigate and implement proper safe guards.

**Comment by rasjani** [comment]
There is infact, server side throttling in telkkarista.com for api calls .. Would be good to get idea what are the limits.

Also, i submitted a feature request to telkkarista.com about possibility to query epg data for multiple pid's in single request - checked last week and there where some changes made for the api to allow multiple pids but backend didnt return multiple epg info's, just for the last one of the passed in array ..

**Comment by rasjani** [comment]
Only thing that currently bombards api backend is for epg data fetching for search results and program lists per channel. Both of these will be implemented in pagination of programs #3 so closing this.

**Comment by grinsted** [comment]
Could you add a setting to disable the epg info calls for the list (while it is great to have, then it is also really slow). It sure would be nice if the API would give you all the descriptions at once (also i would like thumbnails).

**Comment by rasjani** [comment]
Reason why they are slow is being is that initially i was fetching epg data for each epg entry in a separate request, later on telkkarista took this into consideration and they can now be fetched in a single request but as said, search results and program info still uses the "fetch everything on on request" - where server throttling needs to be taken into account - which is the root cause of being very slow .. 

This will be fixed..

But i'll think about making epg fetching as optional.
